<a href="https://colab.research.google.com/github/BeneWim/ACTHProject/blob/Francesca/MET.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
df = pd.read_csv ("/MetObjects.txt")

/tmp/ipython-input-5-1783447767.py:5: DtypeWarning: Columns (5,7,10,11,12,13,14,34,35,36,37,38,39,40,41,42,43,44,45,46) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv ("/MetObjects.txt")

# Neuer Abschnitt

In [10]:
df.head()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 484956 entries, 0 to 484955
Data columns (total 54 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   Object Number            484956 non-null  object
 1   Is Highlight             484956 non-null  bool
 2   Is Timeline Work         484956 non-null  bool
 3   Is Public Domain         484956 non-null  bool
 4   Object ID                484956 non-null  int64
 5   Gallery Number           49541 non-null   object
 6   Department               484956 non-null  object
 7   AccessionYear            481094 non-null  object
 8   Object Name              482690 non-null  object
 9   Title                    456153 non-null  object
 10  Culture                  208190 non-null  object
 11  Period                   91143 non-null   object
 12  Dynasty                  23201 non-null   object
 13  Reign                    11236 non-null   object
 14  Portfolio                26514 non-null   object
 15  Constituent ID           282513 non-null  object
 16  Artist Role              282513 non-null  object
 17  Artist Prefix            282513 non-null  object
 18  Artist Display Name      282513 non-null  object
 19  Artist Display Bio       280423 non-null  object
 20  Artist Suffix            282465 non-null  object
 21  Artist Alpha Sort        282513 non-null  object
 22  Artist Nationality       282513 non-null  object
 23  Artist Begin Date        282513 non-null  object
 24  Artist End Date          282513 non-null  object
 25  Artist Gender            106482 non-null  object
 26  Artist ULAN URL          227441 non-null  object
 27  Artist Wikidata URL      224202 non-null  object
 28  Object Date              471525 non-null  object
 29  Object Begin Date        484956 non-null  int64
 30  Object End Date          484956 non-null  int64
 31  Medium                   477741 non-null  object
 32  Dimensions               409898 non-null  object
 33  Credit Line              484305 non-null  object
 34  Geography Type           59959 non-null   object
 35  City                     32754 non-null   object
 36  State                    2621 non-null    object
 37  County                   8559 non-null    object
 38  Country                  76007 non-null   object
 39  Region                   31500 non-null   object
 40  Subregion                22143 non-null   object
 41  Locale                   15739 non-null   object
 42  Locus                    7518 non-null    object
 43  Excavation               16571 non-null   object
 44  River                    2092 non-null    object
 45  Classification           406239 non-null  object
 46  Rights and Reproduction  24529 non-null   object
 47  Link Resource            484956 non-null  object
 48  Object Wikidata URL      69154 non-null   object
 49  Metadata Date            0 non-null       float64
 50  Repository               484956 non-null  object
 51  Tags                     192455 non-null  object
 52  Tags AAT URL             192455 non-null  object
 53  Tags Wikidata URL        192455 non-null  object
dtypes: bool(3), float64(1), int64(3), object(47)
memory usage: 190.1+ MB

In [12]:
selected_df = df[['Object Name', 'Title', 'Culture']]

In [16]:
selected_df.head(500)

,Object Name,Title,Culture
0,Coin,One-dollar Liberty Head Coin,NaN
1,Coin,Ten-dollar Liberty Head Coin,NaN
2,Coin,Two-and-a-Half Dollar Coin,NaN
3,Coin,Two-and-a-Half Dollar Coin,NaN
4,Coin,Two-and-a-Half Dollar Coin,NaN
...,...,...,...
495,Book,"Book of Common Prayer, Bible, and Book of Psalms",British
496,Bookcase,Bookcase,American
497,Bookcase,Bookcase,American
498,Bookcase,Bookcase,American
499,Bookend,Bookend,British (American market)

In [22]:
selected_df['Object Name'].value_counts(dropna=False).head(50)

Object Name
Print                                       102986
Photograph                                   29451
Drawing                                      26018
Book                                         13397
Kylix fragment                                8926
Piece                                         8621
Fragment                                      7213
Painting                                      6014
Negative                                      5928
Bowl                                          3633
Vase                                          3219
Figure                                        3035
Dress                                         2639
Baseball card                                 2505
Baseball card, print                          2463
Textile fragment                              2301
NaN                                           2266
Plate                                         2230
Ensemble                                      2121
Books Prints Ornament & Architecture          2120
Baseball card, photograph                     2099
Medal                                         1944
Dish                                          1940
Evening dress                                 1885
Print; ephemera                               1667
Panel                                         1660
Hanging scroll                                1618
Carte-de-visite                               1570
Hat                                           1522
Drawing Ornament & Architecture               1516
Print collection ornament & architecture      1479
Ornament                                      1464
Bottle                                        1454
Sculpture                                     1449
Textile sample                                1410
Jar                                           1275
Cup                                           1232
Sword guard (Tsuba)                           1211
Print Ornament & Architecture                 1163
Stereograph                                   1159
Vase fragment                                 1158
Kylix fragments                               1136
Scarab                                        1130
Plaque                                        1125
Knife handle (Kozuka)                         1087
Fan                                           1076
Coin                                          1059
Statuette                                     1006
Sample                                        1005
Pendant                                        994
Name: count, dtype: int64